### ISSUE TITLE
AnyCapes Not Working on 1.17

### ISSUE THREAD

**Issue by Finoway** [PepperCode1/AnyCapes#4]
Hello,

I wanted to use/test AnyCapes in 1.17 but it doesn't work and I wanted to point it out even if you might be aware of it and/or are fixing it. I wanted to add that everyone has capes buggy.

![image](https://user-images.githubusercontent.com/48923336/122445861-46898000-cfa2-11eb-9758-8959de8bf45e.png)

**Comment by PepperCode1** [comment]
Yep, I will release a 1.17 version sometime soon.

**Comment by Cardistymo** [comment]
> Yep, I will release a 1.17 version sometime soon.

pls update!

**Comment by PepperCode1** [comment]
I just released the 1.17 update. You can get it from GitHub Releases or CurseForge, as usual.
